controllers/cliente.py
from flask import Blueprint, render_template, session, redirect, url_for
from model.Producto import Producto
from model.CategoriaProducto import CategoriaProducto
cliente = Blueprint('cliente', __name__)

@cliente.route("/")
def home():
    user = session.get("cliente.auth", None)
    categorias = CategoriaProducto.obtener_categorias()
    productos = Producto.obtener_productos_limite()
    if user:
        return render_template("client/index.html", cliente = user["nombres"], categorias = categorias, productos=productos)
    return render_template("client/index.html", categorias = categorias, productos=productos)

@cliente.route("/productos/<string:categoria>")
def productos_categoria(categoria):
    user = session.get("cliente.auth", None)
    categorias = CategoriaProducto.obtener_categorias()
    productos = Producto.getProductosCategoria(categoria)
    if user:
        return render_template("client/productos.html", cliente = user["nombres"], productos = productos, categoria = categoria, categorias = categorias)
    return render_template("client/productos.html", productos = productos, categoria = categoria, categorias = categorias)

@cliente.route("/formulario_registro_cliente")
def formulario_registro_cliente():
     return render_template("client/registro.html")

@cliente.route("/producto/<int:id>")
def comprar_producto(id):
    user = session.get("cliente.auth", None)
    producto = Producto.obtener_producto_por_id(id)
    cremas = Producto.getProductosCategoria("Cremas")
    if producto is None:
        return redirect(url_for("cliente.home"))
    if user:
        return render_template("client/seleccion-producto.html", cliente = user["nombres"], producto=producto, cremas = cremas)
    return render_template("client/seleccion-producto.html", producto=producto, cremas = cremas)

@cliente.route("/carrito")
def pag_carrito():
    user = session.get("cliente.auth", None)
    if user:
        return render_template("client/carrito.html", cliente = user["nombres"])
    return render_template("client/carrito.html")

@cliente.route("/compra")
def pag_compra():
    user = session.get("cliente.auth", None)
    if user:
        return render_template("client/compra.html", sesion = user, cliente = user["nombres"], apellidos = user["apellidos"], telefono = user["telefono"], dni= user["dni"], idUsuario = user["idUsuario"])
    return render_template("client/compra.html")
# @cliente.route("/<tipo>")
# def verMas(tipo):
#     productos = []
#     if tipo == "simples":
#         productos = Producto.getProductosTipo(1)
#     elif tipo == "mixtas":
#         productos = Producto.getProductosTipo(2)
#     elif tipo == "alopobre":
#         productos = Producto.getProductosTipo(3)
#     elif tipo == "especiales":
#         productos = Producto.getProductosTipo(4)
    
#     return render_template("client/verMas.html", productos = productos)

templates/client/carrito.html
{% extends "client/main.html" %} {% block titulo %} Carrito de compras {%
endblock %} {% block contenido %}

<section class="mt-5 mb-3">
  <main class="mt-4 container">
    <div class="bg-titulo p-2 mb-2">
      <h1 class="mt-2 mb-2">Carrito de compras</h1>
    </div>

    <div class="productos-carrito mb-2 d-flex flex-column gap-3"></div>

    <div id="precio-total" class="mt-4"></div>

    <div class="d-flex justify-content-end gap-2">
      <div class="btn-vaciar-carrito">
        <a class="btn btn-danger" id="vaciar-carrito">Vaciar carrito</a>
      </div>
      <div>
        <a href="{{url_for('cliente.pag_compra')}}" class="btn btn-success"
          >Comprar</a
        >
      </div>
    </div>
  </main>
</section>

<script
  src="{{url_for('static', filename = 'js/mostrarProductos.js')}}"
  type="module"
></script>

{% endblock %}

templates/client/compra.html
{% extends "client/main.html" %} {% block titulo %} Comprar producto {% endblock
%} {% block contenido %}

<section class="mt-5 mb-3 row m-auto">
  <div class="col-lg-6">
    <h3 class="m-3 fs-5 fw-bold">Productos</h3>
    <div class="productos-comprar"></div>
  </div>
  <div class="col-lg-6">
    <h3 class="m-3 fs-5 fw-bold">Datos compra</h3>
    <form
      action=""
      method="post"
      class="d-flex flex-column justify-content-center m-5"
    >
      {% if sesion %}
      <input
        type="hidden"
        name="idUsuario"
        value="{{idUsuario}}"
        id="idUsuario"
      />
      {% endif %}
      <div class="mb-3">
        <label for="dni" class="form-label">Dni:</label>
        {% if sesion %}
        <input
          required
          disabled
          type="number"
          class="form-control"
          name="dni"
          id="dni"
          value="{{dni}}"
        />
        {% else %}
        <input
          required
          type="number"
          class="form-control"
          name="dni"
          id="dni"
        />
        {% endif %}
      </div>
      <div class="mb-3">
        <label for="nombres" class="form-label">Nombres:</label>
        {% if sesion %}
        <input
          required
          disabled
          type="text"
          class="form-control"
          name="nombres"
          id="nombres"
          value="{{cliente + ' ' + apellidos}}"
        />
        {% else %}
        <input
          required
          type="text"
          class="form-control"
          name="nombres"
          id="nombres"
        />
        {% endif %}
      </div>
      <div class="mb-3">
        <label for="telefono" class="form-label">Número telefono:</label>
        {% if sesion %}
        <input
          disabled
          type="number"
          class="form-control"
          name="telefono"
          id="telefono"
          value="{{telefono}}"
        />
        {% else %}
        <input
          type="number"
          class="form-control"
          name="telefono"
          id="telefono"
        />
        {% endif %}
      </div>
      <div class="mb-3">
        <label for="hora-recojo" class="form-label">Hora recojo:</label>
        <input
          type="time"
          class="form-control"
          name="hora-recojo"
          id="hora-recojo"
        />
      </div>
      <div class="form-check">
        <input
          type="checkbox"
          class="form-check-input"
          id="boleta"
          name="boleta"
        />
        <label class="form-check-label" for="exampleCheck1">Boleta</label>
      </div>
      <div class="form-check">
        <input
          type="checkbox"
          class="form-check-input"
          id="billetera-digital"
          name="billeteraDigital"
        />
        <label class="form-check-label" for="exampleCheck1"
          >Billetera digital</label
        >
      </div>

      <div class="text-end mt-2">
        <button id="comprar-producto" type="submit" class="btn btn-success">
          Comprar
        </button>
      </div>
    </form>
  </div>
</section>

<script
  src="{{url_for('static', filename = 'js/mostrarProductosCompra.js')}}"
  type="module"
></script>
<script
  src="{{url_for('static', filename= 'js/comprarProductos.js')}}"
  type="module"
></script>
{% endblock %}

templates/client/index.html
{% extends "client/main.html" %} {% block contenido %}
<section class="seccion-presentacion">
  <div class="seccion-presentacion-content">
    <div class="presentacion-logo">
      <img
        src="{{url_for('static', filename = 'img/logo.jpg')}}"
        alt="Logo Musas"
      />
    </div>
    <div class="presentacion-texto">
      <h2>Las Musas</h2>
      <p>6:00 p.m - 10:00 p.m</p>
    </div>
  </div>
</section>
<!-- Menú de categorias -->
<div class="categorias-content">
  <div class="categorias">
    <div class="categorias-in">
      {% for categoria in categorias %} {% if categoria[1] != "Cremas" %}
      <a
        href="{{url_for('cliente.productos_categoria', categoria = categoria[1])}}"
        class="text-black"
      >
        <div class="categoria-item">
          <!-- <div>
            <img src="#" alt="Categoria" />
          </div> -->
          <p>{{categoria[1]}}</p>
        </div>
      </a>
      {% endif %} {% endfor %}
    </div>
  </div>
</div>

<main class="productos">
  {% for categoria in categorias %} {% if categoria[1] != "Cremas" %}
  <div>
    <div class="cabecera">
      <h2>Productos {{categoria[1]}}</h2>
      <a
        href="{{url_for('cliente.productos_categoria', categoria=categoria[1])}}"
      >
        <button class="ver-mas">Ver más</button>
      </a>
    </div>
    <div class="show-producto d-flex justify-content-around">
      {% for producto in productos %} {% if producto["idCategoria"] ==
      categoria[0] %}
      <div class="card p-0" style="width: 300px">
        <img
          class="card-img-top"
          src="{{url_for('static', filename = 'img/hamburguesas/ha-1.jpg')}}"
          alt=""
        />
        <div class="card-body">
          <h4 class="card-title">{{producto["nombre"]}}</h4>
          <div>
            <p class="card-text">{{producto["descripcion"]}}</p>
            <p class="card-text">Precio: {{producto["precio"]}}</p>
          </div>

          <a
            href="{{url_for('cliente.comprar_producto', id=producto['idProducto'])}}"
            class="btn btn-primary w-100"
            >Comprar</a
          >
        </div>
      </div>

      {% endif %} {% endfor %}
    </div>
  </div>
  {% endif %} {% endfor %}
</main>
{% endblock %}

templates/client/login.html
{% extends "client/main.html" %} {% block titulo %} Registrarse {% endblock %}
{% block contenido %}
<section class="w-50 m-auto mt-5 mb-3 h-100">
  <div class="h-100 d-flex flex-column justify-content-center">
    <h3 class="m-3 fs-5 fw-bold">Iniciar sesión</h3>
    <form
      action="{{url_for('cliente.auth.login')}}"
      method="post"
      class="d-flex flex-column justify-content-center"
    >
      <div class="mb-3">
        <label for="usuario" class="form-label">Dni:</label>
        <input
          required
          type="number"
          class="form-control"
          name="usuario"
          id="dni"
        />
      </div>
      <div class="mb-3">
        <label for="contraseña" class="form-label">Contraseña:</label>
        <input
          type="password"
          class="form-control"
          name="contraseña"
          id="contraseña"
        />
      </div>
      <div class="d-flex justify-content-end gap-2">
        <a
          href="{{url_for('cliente.auth.registro')}}"
          class="btn btn-primary mt-2"
        >
          Registrarse
        </a>
        <button type="submit" class="btn btn-success mt-2">Iniciar</button>
      </div>
    </form>
  </div>
</section>
{% endblock %}

templates/client/main.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700;900&display=swap"
      rel="stylesheet"
    />

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="{{url_for('static', filename = 'styles/normalize.css')}}"
    />
    <link
      rel="stylesheet"
      href="{{url_for('static', filename = 'styles/global.css')}}"
    />
    <!-- <link rel="stylesheet" href="../styles/styles.css" /> -->
    <link
      rel="stylesheet"
      href="{{url_for('static', filename = 'styles/header.css')}}"
    />
    <link
      rel="stylesheet"
      href="{{url_for('static', filename = 'styles/footer.css')}}"
    />
    <link
      rel="stylesheet"
      href="{{url_for('static', filename = 'styles/button-carrito.css')}}"
    />
    <link
      rel="stylesheet"
      href="{{url_for('static', filename = 'styles/categorias.css')}}"
    />
    <link
      rel="stylesheet"
      href="{{url_for('static', filename = 'styles/seccion-presentacion.css')}}"
    />
    <link
      rel="stylesheet"
      href="{{url_for('static', filename = 'styles/mostrar-productos.css')}}"
    />
    <title>Musas</title>
  </head>

  <body>
    <header class="header">
      <div class="contenedor-nav">
        <div class="main-top-left">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="icon icon-tabler icon-tabler-menu-2"
            width="44"
            height="44"
            viewBox="0 0 24 24"
            stroke-width="1.5"
            stroke="#DB4200"
            fill="none"
            stroke-linecap="round"
            stroke-linejoin="round"
          >
            <path stroke="none" d="M0 0h24v24H0z" fill="none" />
            <line x1="4" y1="6" x2="20" y2="6" />
            <line x1="4" y1="12" x2="20" y2="12" />
            <line x1="4" y1="18" x2="20" y2="18" />
          </svg>
        </div>
        <div class="main-top-center">
          <a href="{{url_for('cliente.home')}}">
            <img
              src="{{url_for('static', filename = 'img/logo.jpg')}}"
              alt="Logo"
            />
          </a>
        </div>

        <div class="main-top-right">
          <button class="icono-carrito">
            <a href="{{url_for('cliente.pag_carrito')}}">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                class="icon icon-tabler icon-tabler-shopping-cart"
                width="44"
                height="44"
                viewBox="0 0 24 24"
                stroke-width="1.5"
                stroke="#DB4200"
                fill="none"
                stroke-linecap="round"
                stroke-linejoin="round"
              >
                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                <circle cx="6" cy="19" r="2" />
                <circle cx="17" cy="19" r="2" />
                <path d="M17 17h-11v-14h-2" />
                <path d="M6 5l14 1l-1 7h-13" />
              </svg>
            </a>
          </button>

          {% if cliente: %}
          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="icon icon-tabler icon-tabler-user"
            width="44"
            height="44"
            viewBox="0 0 24 24"
            stroke-width="1.5"
            stroke="#DB4200"
            fill="none"
            stroke-linecap="round"
            stroke-linejoin="round"
          >
            <path stroke="none" d="M0 0h24v24H0z" fill="none" />
            <circle cx="12" cy="7" r="4" />
            <path d="M6 21v-2a4 4 0 0 1 4 -4h4a4 4 0 0 1 4 4v2" />
          </svg>
          <div class="d-flex gap-2 align-items-center">
            <p style="text-transform: uppercase; font-size: 14px">
              {{cliente}}
            </p>
            <a href="{{url_for('cliente.auth.logout')}}" class="btn btn-danger"
              >Cerrar sesión</a
            >
          </div>

          {% else: %}
          <a href="{{url_for('cliente.auth.login')}}">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              class="icon icon-tabler icon-tabler-user"
              width="44"
              height="44"
              viewBox="0 0 24 24"
              stroke-width="1.5"
              stroke="#DB4200"
              fill="none"
              stroke-linecap="round"
              stroke-linejoin="round"
            >
              <path stroke="none" d="M0 0h24v24H0z" fill="none" />
              <circle cx="12" cy="7" r="4" />
              <path d="M6 21v-2a4 4 0 0 1 4 -4h4a4 4 0 0 1 4 4v2" />
            </svg>
          </a>
          {% endif %}
        </div>
      </div>
    </header>
    <!-- Menú deslizante para movil -->
    <div class="menu">
      <div class="shadow-close"></div>
      <div class="menu-content">
        <div class="menu-close">
          <span></span>
        </div>
        <div class="menu-head">
          <a href="index.html" class="menu-head-logo">
            <div>
              <img
                src="{{url_for('static', filename = 'img/logo.jpg')}}"
                alt="Logo"
              />
            </div>
          </a>
          <div class="menu-head-elements-right">
            <button class="cuenta">
              <a href="pag-inicio-sesion.html">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  class="icon icon-tabler icon-tabler-user-circle"
                  width="40"
                  height="40"
                  viewBox="0 0 24 24"
                  stroke-width="1.5"
                  stroke="#FBD357"
                  fill="none"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                >
                  <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                  <circle cx="12" cy="12" r="9" />
                  <circle cx="12" cy="10" r="3" />
                  <path
                    d="M6.168 18.849a4 4 0 0 1 3.832 -2.849h4a4 4 0 0 1 3.834 2.855"
                  />
                </svg>
              </a>
            </button>
          </div>
        </div>
        <div class="menu-body">
          <div class="menu-body-list">
            <ul>
              <li class="list-item">
                <a href="">
                  <span class="item-icon"></span>
                  <span>Nombre item</span>
                </a>
              </li>
              <li class="list-item">
                <a href="">
                  <span class="item-icon"></span>
                  <span>Nombre item</span>
                </a>
              </li>
              <li class="list-item">
                <a href="">
                  <span class="item-icon"></span>
                  <span>Nombre item</span>
                </a>
              </li>
              <li class="list-item">
                <a href="">
                  <span class="item-icon"></span>
                  <span>Nombre item</span>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <!-- Botón flotante para el carrito -->
    <div class="button-carrito">
      <div class="">
        <button type="button" class="btncarrito btncarrito-lg">
          <span class="button-cantidad">0</span>
          VER CARRITO
          <div class="button-precio">
            <p>S/ 0.00</p>
          </div>
        </button>
      </div>
    </div>

    {%block contenido %} {% endblock %}

    <footer class="footer">
      <div class="footer-top">
        <div class="logo-conocenos">
          <a href="{{url_for('cliente.home')}}">
            <img
              src="{{url_for('static', filename = 'img/logo.jpg')}}"
              alt="logo"
            />
          </a>
          <a href="#">
            <h4>Conocenos</h4>
          </a>
        </div>
        <div class="atencion-cliente">
          <h4>Atención al cliente</h4>
          <ul class="footer-links">
            <li>
              <a href="#">Contacto</a>
            </li>
            <li>
              <a href="#">Preguntas frecuentes</a>
            </li>
          </ul>
        </div>
        <div class="d-flex formas-pago">
          <div class="formas-pago-content">
            <h4>Formas de pago</h4>
            <div class="formas-pago-img">
              <img
                src="{{url_for('static', filename = 'img/fp-yape.jpg')}}"
                alt="Yape"
              />
              <img
                src="{{url_for('static', filename = 'img/fp-plin.jpg')}}"
                alt="Plin"
              />
            </div>
          </div>
        </div>
      </div>
      <div class="contenedor-footer">
        <div class="d-flex footer-bottom">
          <p>Musas todos los derechos reservados</p>
          <div class="d-flex redes-sociales">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              class="icon icon-tabler icon-tabler-brand-facebook"
              width="32"
              height="32"
              viewBox="0 0 24 24"
              stroke-width="1"
              stroke="#ffffff"
              fill="none"
              stroke-linecap="round"
              stroke-linejoin="round"
            >
              <path stroke="none" d="M0 0h24v24H0z" fill="none" />
              <path
                d="M7 10v4h3v7h4v-7h3l1 -4h-4v-2a1 1 0 0 1 1 -1h3v-4h-3a5 5 0 0 0 -5 5v2h-3"
              />
            </svg>

            <svg
              xmlns="http://www.w3.org/2000/svg"
              class="icon icon-tabler icon-tabler-brand-instagram"
              width="32"
              height="32"
              viewBox="0 0 24 24"
              stroke-width="1"
              stroke="#ffffff"
              fill="none"
              stroke-linecap="round"
              stroke-linejoin="round"
            >
              <path stroke="none" d="M0 0h24v24H0z" fill="none" />
              <rect x="4" y="4" width="16" height="16" rx="4" />
              <circle cx="12" cy="12" r="3" />
              <line x1="16.5" y1="7.5" x2="16.5" y2="7.501" />
            </svg>
          </div>
        </div>
      </div>
    </footer>

    <!-- <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
      crossorigin="anonymous"
    ></script> -->
    <script src="{{url_for('static', filename = 'js/header.js')}}"></script>
    <script src="{{url_for('static', filename = 'js/categorias.js')}}"></script>
  </body>
</html>

templates/client/productos.html
{% extends "client/main.html" %} {% block titulo %} Registrarse {% endblock %}
{% block contenido %}
<div class="categorias-content pt-5">
  <div class="categorias">
    <div class="categorias-in">
      {% for categoria in categorias %} {% if categoria[1] != "Cremas" %}
      <a
        href="{{url_for('cliente.productos_categoria', categoria = categoria[1])}}"
        class="text-black"
      >
        <div class="categoria-item">
          <!-- <div>
            <img src="#" alt="Categoria" />
          </div> -->
          <p>{{categoria[1]}}</p>
        </div>
      </a>
      {% endif %} {% endfor %}
    </div>
  </div>
</div>
<section class="mt-1 mb-3">
  <h3>Productos {{categoria}}</h3>

  <div class="d-flex flex-wrap gap-2 justify-content-center mt-3">
    {% for producto in productos %}
    <div class="card" style="width: 300px">
      <img
        class="card-img-top"
        src="{{url_for('static', filename = 'img/hamburguesas/ha-1.jpg')}}"
        alt=""
      />
      <div class="card-body">
        <h4 class="card-title">{{producto["nombre"]}}</h4>
        <div>
          <p class="card-text">{{producto["descripcion"]}}</p>
          <p class="card-text">Precio: {{producto["precio"]}}</p>
        </div>

        <a
          href="{{url_for('cliente.comprar_producto', id=producto['idProducto'])}}"
          class="btn btn-primary w-100"
          >Comprar</a
        >
      </div>
    </div>

    {% endfor %}
  </div>
</section>

{% endblock %}

templates/client/registro.html
{% extends "client/main.html" %} {% block titulo %} Registrarse {% endblock %}
{% block contenido %}
<section class="w-50 m-auto mt-5 mb-3">
  <h3 class="m-3 fs-5 fw-bold">Registro</h3>
  <form
    action="{{url_for('cliente.auth.registro')}}"
    method="post"
    class="d-flex flex-column justify-content-center"
  >
    <div class="mb-3">
      <label for="dni" class="form-label">Dni:</label>
      <input required type="number" class="form-control" name="dni" id="dni" />
    </div>
    <div class="mb-3">
      <label for="nombres" class="form-label">Nombres:</label>
      <input type="text" class="form-control" name="nombres" id="nombres" />
    </div>
    <div class="mb-3">
      <label for="apellidos" class="form-label">Apellidos:</label>
      <input type="text" class="form-control" name="apellidos" id="apellidos" />
    </div>
    <div class="mb-3">
      <label for="correo" class="form-label">Correo:</label>
      <input type="email" class="form-control" name="correo" id="correo" />
    </div>
    <div class="mb-3">
      <label for="telefono" class="form-label">Teléfono:</label>
      <input type="tel" class="form-control" name="telefono" id="telefono" />
    </div>
    <div class="mb-3">
      <label for="contraseña" class="form-label">Nueva contraseña:</label>
      <input
        type="password"
        class="form-control"
        name="contraseña"
        id="contraseña"
      />
    </div>
    <div class="d-flex justify-content-end gap-2">
      <a href="{{url_for('cliente.auth.login')}}" class="btn btn-primary mt-2"
        >Iniciar sesión</a
      >
      <button type="submit" class="btn btn-success mt-2">Registrarse</button>
    </div>
  </form>
</section>
{% endblock %}

templates/client/seleccion-producto.html
{% extends "client/main.html" %} {% block titulo %} Registrarse {% endblock %}
{% block contenido %}
<section class="mt-5 mb-3 container">
  <h2 class="">{{producto["nombre"]}}</h2>
  <div class="w-auto m-auto">
    <div class="row align-items-center justify-content-md-center m-auto">
      <div class="col-sm-6 text-center">
        <img
          src="{{url_for('static', filename = 'img/hamburguesas/h-2.jpg')}}"
          alt=""
          class="rounded"
          style="width: 250px"
        />
      </div>

      <div class="col-sm-6 text-center">
        <div class="informacion-producto-ingredientes">
          <p>{{producto["descripcion"]}}</p>
        </div>

        <p class="informacion-producto-precio">
          <span>S/.</span>{{producto["precio"]}}
        </p>
      </div>
    </div>
  </div>

  <div class="main-content-personalizar">
    <h3 class="text-start">Personaliza</h3>
    <div class="personalizar-salsas">
      <h4>Elegir salsas</h4>
      <div class="d-flex justify-content-around">
        {% for crema in cremas %}
        <div class="custom-item">
          <div class="custom-item__img">
            <img
              src="{{url_for('static', filename = 'img/personalizar/mayonesa.jpg')}}"
              alt=""
              width="68"
              height="68"
            />
          </div>
          <p>{{crema["nombre"]}}</p>
          <p class="precio-agregar"><span>S/.</span>{{crema["precio"]}}</p>
          <input
            type="checkbox"
            name="crema"
            value="{{crema['idProducto']}}"
            class="valores"
          />
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
  <div class="text-end">
    <a
      id="agregar-carrito"
      href="{{url_for('cliente.pag_carrito')}}"
      class="btn btn-success text-center"
      >Agregar al carrito</a
    >
  </div>

  <script
    src="{{url_for('static', filename = 'js/guardarProductos.js')}}"
    type="module"
  ></script>
</section>
{% endblock %}